### PR TITLE
feat: add alignment and spacing params

### PR DESCRIPTION
**Pull request by reuschj**
Adds alignment and spacing params to the wrapper view to pass to underlying VStack or HStack.

### CODE REVIEW

**Comment by kcochibili** [comment]
It looks great and I think it is good to merge to the main branch now.  I really love your coding style, So much to learn from it!

**Comment by reuschj** [comment]
Cool... thanks! I did a bit more testing and found a few issues. The `GeometryReader` changes the behavior of the wrapped VStack/HStack a bit. Spacing works well, but alignment doesn't really work as expected. Will tinker around a bit and get it working.

**Comment by reuschj** [comment]
Ok... this seems to work. To restore the expected behavior, I have to wrap the embedded VStack or HStack in a frame matching the geometry.

**Comment by reuschj** [comment]
Will merge. If you try it out and have any issues, we can do a fix version.

**Comment by kcochibili** [comment]
I noticed that spacing  problem on my side but I  quickly ignored it, thinking it wasn't a major deal breaker. I think its a genius how you quickly figured out a solution to it.

I am yet to test everything, I will give you feedback on how it runs on my end once I do. 

Thanks again for this little big library

**Pull request merged**
